"""Merge the LoRA adapter, convert to GGUF, and register a loopback Ollama tag.

Training-only. The result is a *measurement* artifact: an Ollama/GGUF tag is
not the OVMS/NPU INT4 tuple `npu-micro-extract-qwen3-0.6b` names, so passing a
gate here says nothing about that profile. Keep `gatePassed: false` until the
serving tuple itself is measured.

`--no-adapter` exports the untouched base through the identical path, so the
control and the candidate differ by the adapter and nothing else — not by
quantisation, not by template, not by conversion tool.

Ollama 0.32.9 refuses `Qwen3ForCausalLM` safetensors ("unsupported
architecture"), so the merged weights go through llama.cpp's converter first.
That tool is not on PyPI; fetch a pinned release once and point `--llama-cpp`
at it (see README.md). f16 is deliberate: quantising here would add a second
variable to a run whose whole point is measuring the adapter.

Usage:
    python export_ollama.py --tag cortex-micro-extract-0.6b:v1
    python export_ollama.py --no-adapter --tag cortex-micro-extract-0.6b:base
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

import torch
from transformers import AutoModelForCausalLM

# LoRA does not touch the tokenizer, so these are copied from upstream rather
# than re-serialised. Under transformers 5 `save_pretrained` moves the chat
# template into `chat_template.jinja` and omits `vocab.json` / `merges.txt`;
# llama.cpp reads the template out of `tokenizer_config.json` and the BPE vocab
# out of that pair, so a re-serialised tokenizer silently changes both the
# served prompt prefix and the vocab path away from what was trained.
TOKENIZER_FILES = (
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.json",
    "merges.txt",
    "generation_config.json",
)

DEFAULT_LLAMA_CPP = (
    Path(os.environ.get("LOCALAPPDATA", "."))
    / "cortex-loom"
    / "fine-tune"
    / "llama.cpp-b10434"
)

MODELFILE = """# Generated by scripts/fine-tune/export_ollama.py. Measurement artifact only.
FROM {source}
PARAMETER temperature 0
"""


def merge(base: str, adapter: Path | None, target: Path) -> None:
    model = AutoModelForCausalLM.from_pretrained(base, dtype=torch.float32)
    if adapter is not None:
        from peft import PeftModel

        model = PeftModel.from_pretrained(model, str(adapter))
        model = model.merge_and_unload()
    model = model.to(torch.float16)
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    model.save_pretrained(target, safe_serialization=True)
    copy_tokenizer(base, target)


def copy_tokenizer(base: str, target: Path) -> None:
    """Copy the upstream tokenizer verbatim. See `TOKENIZER_FILES`."""
    from huggingface_hub import snapshot_download

    snapshot = Path(snapshot_download(base, allow_patterns=list(TOKENIZER_FILES)))
    for name in TOKENIZER_FILES:
        source = snapshot / name
        if source.exists():
            shutil.copy2(source, target / name)
    # An out-of-line template would be a second, disagreeing source of truth.
    (target / "chat_template.jinja").unlink(missing_ok=True)


def to_gguf(llama_cpp: Path, source: Path, target: Path) -> None:
    converter = llama_cpp / "convert_hf_to_gguf.py"
    if not converter.exists():
        raise SystemExit(
            f"no converter at {converter}; see scripts/fine-tune/README.md for the pinned fetch"
        )
    completed = subprocess.run(
        [
            sys.executable,
            str(converter),
            str(source),
            "--outfile",
            str(target),
            "--outtype",
            "f16",
        ],
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(f"convert_hf_to_gguf.py failed with {completed.returncode}")


def create_tag(tag: str, source: Path, modelfile: Path) -> int:
    modelfile.write_text(MODELFILE.format(source=source.name), encoding="utf-8")
    print(f"modelfile -> {modelfile}")
    ollama = shutil.which("ollama")
    if ollama is None:
        print("ollama not on PATH; create the tag manually:")
        print(f"  ollama create {tag} -f {modelfile}")
        return 1
    completed = subprocess.run(
        [ollama, "create", tag, "-f", str(modelfile)],
        check=False,
        cwd=str(modelfile.parent),
    )
    return completed.returncode


def main() -> int:
    repo_default = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=repo_default)
    parser.add_argument("--run", type=Path, default=None)
    parser.add_argument("--base", default="Qwen/Qwen3-0.6B")
    parser.add_argument("--tag", default="cortex-micro-extract-0.6b:v1")
    parser.add_argument("--adapter", type=Path, default=None)
    parser.add_argument("--no-adapter", action="store_true")
    parser.add_argument("--llama-cpp", type=Path, default=DEFAULT_LLAMA_CPP)
    parser.add_argument("--skip-create", action="store_true")
    parser.add_argument(
        "--keep-merged",
        action="store_true",
        help="keep the ~1.2 GB safetensors copy after the GGUF exists",
    )
    args = parser.parse_args()

    repo: Path = args.repo.resolve()
    run: Path = (args.run or repo / ".cortex-loom/fine-tune/runs/micro-extract-lora").resolve()
    adapter = None if args.no_adapter else (args.adapter or run / "adapter")
    if adapter is not None and not adapter.exists():
        raise SystemExit(f"no adapter at {adapter}; run train_lora.py first")

    stem = args.tag.replace(":", "-")
    merged = run / ("base" if args.no_adapter else "merged")
    gguf = run / f"{stem}.f16.gguf"
    print(f"merging {args.base} + {adapter or 'nothing'} -> {merged}")
    merge(args.base, adapter, merged)
    print(f"converting -> {gguf}")
    to_gguf(args.llama_cpp, merged, gguf)
    if not args.keep_merged:
        shutil.rmtree(merged, ignore_errors=True)
    if args.skip_create:
        print(f"exported {gguf}; skipping ollama create")
        return 0
    return create_tag(args.tag, gguf, run / f"Modelfile.{stem}")


if __name__ == "__main__":
    sys.exit(main())
