//! Bounded, deterministic edit map from evidence that survived compilation.
//! It identifies source to review; it never claims a change has been made.

use std::collections::HashSet;
use std::path::{Component, Path};

use serde::{Deserialize, Serialize};

use crate::{CoverageCertificate, EvidenceDerivation, EvidenceFacet, EvidenceItem, EvidenceState};

const MAX_SOURCE_TARGETS: usize = 4;
const MAX_TEST_TARGETS: usize = 3;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ChangePlanStatus {
    ReadyForUpstreamReview,
    NeedsEvidence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SourceTarget {
    pub path: String,
    pub start_line: u32,
    pub end_line: u32,
    pub evidence_id: String,
    pub facet: EvidenceFacet,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ChangePlan {
    pub status: ChangePlanStatus,
    pub source_targets: Vec<SourceTarget>,
    pub test_targets: Vec<SourceTarget>,
    pub missing_facets: Vec<String>,
    pub next_expansion: Option<String>,
    pub review_required: bool,
}

/// Form a coding-agent map from selected exact source and a coverage ledger.
/// The map's IDs and ranges are copied from evidence, never generated by a model.
#[must_use]
pub fn build_change_plan(
    task: &str,
    selected: &[EvidenceItem],
    certificate: Option<&CoverageCertificate>,
    evidence_sufficient: bool,
) -> ChangePlan {
    let mut candidates = Vec::new();
    let mut seen = HashSet::new();
    for item in selected {
        if item.state != EvidenceState::Verified
            || item.derivation != Some(EvidenceDerivation::ExactSource)
        {
            continue;
        }
        let Some(locator) = &item.locator else {
            continue;
        };
        let Some(path) = locator
            .path
            .as_deref()
            .filter(|path| safe_relative_path(path))
        else {
            continue;
        };
        let Some(start_line) = locator.start_line else {
            continue;
        };
        let end_line = locator.end_line.unwrap_or(start_line);
        if start_line == 0 || end_line < start_line || !seen.insert(item.id.as_str()) {
            continue;
        }
        let target = SourceTarget {
            path: path.to_owned(),
            start_line,
            end_line,
            evidence_id: item.id.clone(),
            facet: item.facet.unwrap_or_default(),
        };
        candidates.push((
            relevance(task, item, path),
            target,
            item.content.contains("#[test]"),
        ));
    }
    candidates.sort_by_key(|candidate| std::cmp::Reverse(candidate.0));
    let strongest = candidates.first().map_or(0, |candidate| candidate.0);
    let eligible: Vec<_> = candidates
        .into_iter()
        .filter(|(score, target, _)| strongest < 60 || *score >= 20 || is_test_path(&target.path))
        .collect();
    let mut source_targets = Vec::new();
    let mut test_targets = Vec::new();
    for (_, target, inline_tests) in &eligible {
        // A strong named owner excludes incidental fixture strings in other
        // crates. Unnamed cross-file changes retain the wider candidate set.
        if (is_test_path(&target.path) || *inline_tests)
            && test_targets.len() < MAX_TEST_TARGETS
            && !test_targets
                .iter()
                .any(|existing: &SourceTarget| existing.path == target.path)
        {
            test_targets.push(target.clone());
        }
        if !is_test_path(&target.path)
            && source_targets.len() < MAX_SOURCE_TARGETS
            && !source_targets
                .iter()
                .any(|existing: &SourceTarget| existing.path == target.path)
        {
            source_targets.push(target.clone());
        }
    }
    add_complementary_windows(&eligible, &mut source_targets, &test_targets);
    let missing_facets = certificate.map_or_else(Vec::new, |value| value.missing.clone());
    let next_expansion = certificate
        .and_then(CoverageCertificate::next_expansion)
        .map(CoverageCertificate::expand_handle)
        .map(str::to_owned);
    let sufficient =
        evidence_sufficient && certificate.is_some_and(|value| value.sufficient && !value.stale);
    ChangePlan {
        status: if sufficient && !source_targets.is_empty() {
            ChangePlanStatus::ReadyForUpstreamReview
        } else {
            ChangePlanStatus::NeedsEvidence
        },
        source_targets,
        test_targets,
        missing_facets,
        next_expansion,
        review_required: true,
    }
}

fn add_complementary_windows(
    eligible: &[(u32, SourceTarget, bool)],
    source_targets: &mut Vec<SourceTarget>,
    test_targets: &[SourceTarget],
) {
    // A second window can carry a constant above the owner definition.
    // Keep inline test windows in test_targets so they do not displace it.
    for (_, target, _) in eligible {
        if source_targets.len() >= MAX_SOURCE_TARGETS {
            break;
        }
        if test_targets
            .iter()
            .any(|test| test.evidence_id == target.evidence_id)
        {
            continue;
        }
        let same: Vec<_> = source_targets
            .iter()
            .filter(|existing| existing.path == target.path)
            .collect();
        if same.len() != 1 || is_test_path(&target.path) {
            continue;
        }
        let first = same[0];
        if target.start_line < first.start_line || target.end_line > first.end_line {
            source_targets.push(target.clone());
        }
    }
}

fn relevance(task: &str, item: &EvidenceItem, path: &str) -> u32 {
    let compact_task = compact(task);
    let stem = Path::new(path)
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or_default();
    let mut score = if stem.len() >= 5 && compact_task.contains(&compact(stem)) {
        80
    } else {
        0
    };
    if item.facet == Some(EvidenceFacet::Definition) {
        score += 40;
    }
    let path_lower = path.to_ascii_lowercase();
    let content_lower = item.content.to_ascii_lowercase();
    for word in task
        .split(|character: char| !character.is_alphanumeric() && character != '_')
        .map(str::to_ascii_lowercase)
        .filter(|word| {
            word.len() >= 3
                && !matches!(
                    word.as_str(),
                    "the" | "and" | "tests" | "test" | "fix" | "add" | "code" | "src"
                )
        })
    {
        if path_lower.contains(&word) {
            score += 20;
        } else if word.len() >= 5 && content_lower.contains(&word) {
            score += 2;
        }
    }
    score
}

fn compact(text: &str) -> String {
    text.chars()
        .filter(|character| character.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

#[must_use]
pub fn safe_relative_path(path: &str) -> bool {
    let parsed = Path::new(path);
    parsed.is_relative()
        && parsed
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
}

fn is_test_path(path: &str) -> bool {
    let lower = path.to_ascii_lowercase();
    lower.contains("/tests/")
        || lower.ends_with("/tests.rs")
        || lower.ends_with("_test.rs")
        || lower.ends_with("_tests.rs")
        || lower.ends_with(".test.ts")
        || lower.ends_with(".test.tsx")
        || lower.ends_with(".spec.ts")
        || lower.ends_with(".spec.tsx")
        || lower.ends_with("_test.py")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{EvidenceLocator, EvidencePriority, EvidenceState};

    fn source(id: &str, path: &str, derivation: EvidenceDerivation) -> EvidenceItem {
        let mut item = EvidenceItem::new(
            id,
            path,
            "fn current() {}",
            EvidencePriority::High,
            EvidenceState::Verified,
        );
        item.derivation = Some(derivation);
        item.locator = Some(EvidenceLocator {
            path: Some(path.to_owned()),
            start_line: Some(12),
            end_line: Some(24),
            ..EvidenceLocator::default()
        });
        item
    }

    #[test]
    fn map_uses_only_delivered_exact_source_and_keeps_test_anchor() {
        let items = [
            source("ev_source", "src/store.rs", EvidenceDerivation::ExactSource),
            source("ev_test", "src/tests.rs", EvidenceDerivation::ExactSource),
            source("ev_search", "src/false.rs", EvidenceDerivation::Search),
            source(
                "ev_escape",
                "../outside.rs",
                EvidenceDerivation::ExactSource,
            ),
        ];
        let certificate = CoverageCertificate {
            sufficient: true,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan(
            "Change src/store.rs and tests",
            &items,
            Some(&certificate),
            true,
        );
        assert_eq!(map.status, ChangePlanStatus::ReadyForUpstreamReview);
        assert_eq!(map.source_targets.len(), 1);
        assert_eq!(map.test_targets.len(), 1);
        assert_eq!(map.source_targets[0].evidence_id, "ev_source");
        assert!(map.review_required);
    }

    #[test]
    fn missing_coverage_keeps_expansion_visible() {
        let certificate = CoverageCertificate {
            missing: vec![crate::FACET_DEFINITION.to_owned()],
            sufficient: false,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan("Fix source", &[], Some(&certificate), false);
        assert_eq!(map.status, ChangePlanStatus::NeedsEvidence);
        assert_eq!(map.next_expansion.as_deref(), Some("complete_definition"));
    }

    #[test]
    fn named_owner_drops_incidental_fixture_sources() {
        let mut owner = source(
            "ev_owner",
            "crates/cortex-mcp/src/runtime/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        owner.facet = Some(EvidenceFacet::Definition);
        owner.content = "impl PacketStore {\n#[test]\nfn evicts_oldest() {}\n}".to_owned();
        let mut fixture = source(
            "ev_fixture",
            "crates/cortex-weavatrix/src/compile/certificate.rs",
            EvidenceDerivation::ExactSource,
        );
        fixture.content = "let sample = \"PacketStore\";".to_owned();
        let certificate = CoverageCertificate {
            sufficient: true,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan(
            "Fix PacketStore eviction order and update tests",
            &[owner, fixture],
            Some(&certificate),
            true,
        );
        assert_eq!(map.source_targets.len(), 1);
        assert_eq!(map.source_targets[0].evidence_id, "ev_owner");
        assert_eq!(map.test_targets.len(), 1);
        assert_eq!(map.test_targets[0].evidence_id, "ev_owner");
    }

    #[test]
    fn facet_ledger_cannot_override_missing_source_requirement() {
        let owner = source("ev_owner", "src/store.rs", EvidenceDerivation::ExactSource);
        let certificate = CoverageCertificate {
            sufficient: true,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan("Change store.rs", &[owner], Some(&certificate), false);
        assert_eq!(map.status, ChangePlanStatus::NeedsEvidence);
    }

    #[test]
    fn complementary_window_keeps_constant_above_named_owner() {
        let mut owner = source(
            "ev_owner",
            "src/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        owner.facet = Some(EvidenceFacet::Definition);
        let mut head = source(
            "ev_head",
            "src/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        head.locator.as_mut().unwrap().start_line = Some(1);
        head.locator.as_mut().unwrap().end_line = Some(20);
        let certificate = CoverageCertificate {
            sufficient: true,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan(
            "Rename PacketStore MAX_PACKETS",
            &[owner, head],
            Some(&certificate),
            true,
        );
        assert_eq!(map.source_targets.len(), 2);
        assert_eq!(map.source_targets[1].start_line, 1);
    }

    #[test]
    fn inline_test_window_does_not_displace_constant_above_owner() {
        let mut owner = source(
            "ev_owner",
            "src/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        owner.facet = Some(EvidenceFacet::Definition);
        let mut head = source(
            "ev_head",
            "src/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        head.locator.as_mut().unwrap().start_line = Some(1);
        head.locator.as_mut().unwrap().end_line = Some(20);
        let mut tests = source(
            "ev_tests",
            "src/packet_store.rs",
            EvidenceDerivation::ExactSource,
        );
        tests.content = "#[cfg(test)]\n#[test]\nfn packet_store_test() {}".to_owned();
        tests.locator.as_mut().unwrap().start_line = Some(96);
        tests.locator.as_mut().unwrap().end_line = Some(128);
        let certificate = CoverageCertificate {
            sufficient: true,
            ..CoverageCertificate::default()
        };
        let map = build_change_plan(
            "Rename PacketStore MAX_PACKETS and update tests",
            &[owner, tests, head],
            Some(&certificate),
            true,
        );
        assert_eq!(map.test_targets[0].evidence_id, "ev_tests");
        assert_eq!(map.source_targets[1].evidence_id, "ev_head");
    }
}
