use crate::{ActivationHints, SequenceTemplate, TemplateVersion};

pub(crate) static TEMPLATES: [SequenceTemplate; 7] = [
    SequenceTemplate {
        id: "discover-and-plan",
        version: TemplateVersion::new(1, 0, 0),
        title: "Discover and Plan",
        description: "Turn an unclear task into a bounded evidence-backed plan.",
        markdown: include_str!("../templates/discover-and-plan.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["analysis", "planning", "implementation"],
            intents: &["discover", "plan", "design"],
            risks: &["low", "medium", "high"],
            mutation: false,
            evidence_classes: &["source", "dependents", "contracts"],
            lexical_cues: &["plan", "design", "understand", "impact"],
        },
    },
    SequenceTemplate {
        id: "bounded-implementation",
        version: TemplateVersion::new(1, 0, 0),
        title: "Bounded Implementation",
        description: "Implement approved work in small test-led slices.",
        markdown: include_str!("../templates/bounded-implementation.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["implementation", "bugfix", "refactor"],
            intents: &["implement", "fix", "change"],
            risks: &["low", "medium", "high"],
            mutation: true,
            evidence_classes: &["source", "dependents", "tests"],
            lexical_cues: &["implement", "build", "fix", "refactor"],
        },
    },
    SequenceTemplate {
        id: "root-cause-debugging",
        version: TemplateVersion::new(1, 0, 0),
        title: "Root Cause Debugging",
        description: "Diagnose a reproducible failure before correcting it.",
        markdown: include_str!("../templates/root-cause-debugging.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["debugging", "incident", "test-failure"],
            intents: &["diagnose", "debug", "explain", "fix"],
            risks: &["low", "medium", "high", "critical"],
            mutation: true,
            evidence_classes: &["source", "callers", "runtime", "tests"],
            lexical_cues: &["failure", "error", "bug", "hang", "root cause"],
        },
    },
    SequenceTemplate {
        id: "review-and-correct",
        version: TemplateVersion::new(1, 0, 0),
        title: "Review and Correct",
        description: "Request grounded review and correct verified findings.",
        markdown: include_str!("../templates/review-and-correct.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["review", "implementation"],
            intents: &["review", "critique", "address-feedback"],
            risks: &["low", "medium", "high"],
            mutation: true,
            evidence_classes: &["diff", "source", "tests", "contracts"],
            lexical_cues: &["review", "feedback", "comment", "correct"],
        },
    },
    SequenceTemplate {
        id: "verify-and-integrate",
        version: TemplateVersion::new(1, 0, 0),
        title: "Verify and Integrate",
        description: "Prove completion and integrate under explicit authority.",
        markdown: include_str!("../templates/verify-and-integrate.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["verification", "integration", "release"],
            intents: &["verify", "commit", "merge", "release"],
            risks: &["low", "medium", "high", "critical"],
            mutation: true,
            evidence_classes: &["tests", "diff", "repository-state"],
            lexical_cues: &["verify", "finish", "commit", "merge", "release"],
        },
    },
    SequenceTemplate {
        id: "parallel-investigation",
        version: TemplateVersion::new(1, 0, 0),
        title: "Parallel Investigation",
        description: "Split independent read-only questions and synthesize evidence.",
        markdown: include_str!("../templates/parallel-investigation.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["analysis", "investigation", "review"],
            intents: &["parallelize", "compare", "investigate"],
            risks: &["low", "medium"],
            mutation: false,
            evidence_classes: &["source", "contracts", "runtime"],
            lexical_cues: &["independent", "parallel", "compare", "investigate"],
        },
    },
    SequenceTemplate {
        id: "sequence-authoring",
        version: TemplateVersion::new(1, 0, 0),
        title: "Sequence Authoring",
        description: "Create or revise an editable sequence from observed failures.",
        markdown: include_str!("../templates/sequence-authoring.md"),
        changelog: "Initial Cortex-native sequence.",
        activation: ActivationHints {
            task_classes: &["methodology", "authoring", "evaluation"],
            intents: &["author-sequence", "edit-sequence", "adapt-methodology"],
            risks: &["low", "medium", "high"],
            mutation: true,
            evidence_classes: &["run-history", "benchmarks", "graph"],
            lexical_cues: &["sequence", "workflow", "skill", "template"],
        },
    },
];
